# Site settings
title: Robofont Mechanic
email: your-email@domain.com
description:
baseurl: ""
url: http://blog.robofontmechanic.com # the base hostname & protocol for your site
twitter_username: rfmechanic
github_username:  jackjennings/Mechanic
environment: production

# Build settings
markdown: kramdown

ga_id: UA-41381381-2

exclude:
  - script
  - Gemfile*
  - README*
